### ISSUE TITLE
Can we use The latest stable release of WordPress?

### ISSUE THREAD

**Issue by yolateng0** [YunoHost-Apps/wordpress_ynh#16]
https://wordpress.org/latest.tar.gz

**Comment by maniackcrudelis** [comment]
Do you would said in the install script?

Technically, yes it's possible. But, it's better to use a precise version of wordpress instead of the lastest, because the install script works with this version. But, I don't know if the last version works also.

So, I prefer to fix a version and update the whole package, instead to have, eventually, a breaked package.

If it's really important now, I can make a upgrade of the package.

**Comment by yolateng0** [comment]
the last version works ;-)

**Comment by maniackcrudelis** [comment]
Hi,

I seen the last version, 4.7.2 at now, is a security update. So I did an upgrade of the package to this version.

But, as you can see on the last commit, this version doesn't work without some corrections. It's for that I prefer to use a fixed version.

However, to upgrade your wordpress, use the internal upgrade system of wordpress. Upgrade of the package doesn't affect directly wordpress.

**Comment by yolateng0** [comment]
Effectivement j'ai "upgradé"  directement par l'application. C'était réellement un questionnement suite au problèmes de sécurités récurents  depuis les dernières versions de Wordpress. Des plugins existent aussi.

Indeed I have upgraded directly by the application. It was really a question of recurrent security problems since the latest versions of Wordpress. Plugins also exists to.

**Comment by yolateng0** [comment]
merci à vous @maniackcrudelis @opi @alexAubin @Kloadut and @all pour ce projet <3
