### ISSUE TITLE
authldap plugin is deprecated

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/wordpress_ynh#235]
### Describe the bug

[AuthLDAP plugin has been deprecated as of 2024-03-07](https://wordpress.org/plugins/authldap/). This prevents any new app install, at least.

### Logs

https://paste.yunohost.org/raw/ucafizavog

**Comment by ghost** [comment]
Thank you for working on this! It's totally broken until this change is published.

**Comment by RaggedStaff** [comment]
Just looking & authLDAP has been reinstated following a review by WordPress :shrug: 

I've just successfully installed WP through Yunohost & it all seems fine, which I'm quite relieved about, because the options for wpdirauth are very different & when I tried to set it up, it seemed to keep breaking my server. :roll_eyes:

**Comment by tituspijean** [comment]
Since the link I provided does not explain at all ***why*** the extension was ever temporarily removed, I investigated a bit: https://github.com/heiglandreas/authLdap/issues/237#issuecomment-1983919762

TL;DR: CVE drama and debatable XSS and CSRF vulnerabilities. Issue resolved. 😄
