### ISSUE TITLE
~Security~ php7.0

### ISSUE THREAD

**Issue by ladu63** [YunoHost-Apps/wordpress_ynh#95]
Hello,
Wordpress indicates in the "site health" menu that PHP requires an upgrade.
Can it be upgraded without breaking Yunohost?
Yunohost version : 3.7.1.1 FR
Wordpress version : 5.4 FR
Thank's a lot
Have a nice day
Laurent
![Annotation 2020-04-28 104159](https://user-images.githubusercontent.com/44879329/80466497-ee766100-893c-11ea-8eb2-2cd7a42ba0e3.jpg)

**Comment by maniackcrudelis** [comment]
YunoHost currently runs on Debian Stretch, which uses php7.0
Thus, Wordpress uses php7.0

That won't change until the migration to Debian Buster.

**Comment by moeenio** [comment]
I'm running on Raspbian Stretch, and I have php7.4 packages (i don't know where they come from though)
What I've done to make wordpress use the newer version is to change the nginx config to use the global php7.4 socket instead of the 7.0 one for wordpress that the script automatically creates : 
```
...
location ~ [^/]\.php(/|$) {
           ...
           fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
           fastcgi_index index.php;
           ...
       }
...
```
To check if you have php7.4 packages, you can do :
```
dpkg --get-selections | grep php7.4
```
If they show, that means they are installed.
I also had to change the owner of the wordpress files to www-data iirc.

@ladu63

**Comment by moeenio** [comment]
I know where they come from : the `https://packages.sury.org/php/` apt repository. So you can add that to your `sources.list.d`

**Comment by kay0u** [comment]
Don't do that! If you have installed php7.4, it's either another app that depends on it, or an app that uses sury in the wrong way, but don't add sury by hand or you risk breaking many other apps you have installed.

When an app installs sury (for another version of php), Yunohost handles it and puts some priorities on packages to avoid a lot of bugs.

If you absolutely want a newer version of php, you can switch to buster which is in beta test: https://forum.yunohost.org/t/beta-testing-for-yunohost-4-0-on-debian-buster-and-migration-shipped-in-yunohost-3-8-5/11914

But there is no problem to still use php7.0

**Comment by moeenio** [comment]
Well I didn't add it manually, it was another app. And for now, I don't have issues with that
